version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/containers/economic-tools/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/devcontainers/economic-tools/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
